name: treding
version: 1.0.0+1
publish_to: none
description: A new Flutter Treding app
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_feather_icons: ^2.0.0+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/gg.png



